<?php

return [
    'Activitati Interne' => [
        '1000' => 'Alte servicii (Activitati Interne)',
        '1010' => 'Calendar Activitati (Activitati Interne)',
        '1020' => 'Curatatorie (Activitati Interne)',
        '1030' => 'Deschideri sedii (Activitati Interne)',
        '1040' => 'Evenimente (Activitati Interne)',
        '1050' => 'Reinnoire domenii (Activitati Interne)',
        '1060' => 'Relocari sedii (Activitati Interne)',
        '1070' => 'Teambuilding (Activitati Interne)',
        '1080' => 'Verificari Sedii (Activitati Interne)',
        '1090' => 'Workshops (Activitati Interne)',
    ],
    'Amenzi, penalitati' => [
        '2000' => 'Amenzi (Amenzi, penalitati)',
        '2010' => 'Executari de intarziere (Amenzi, penalitati)',
        '2020' => 'Penalitati (Amenzi, penalitati)',
        '2030' => 'Penalitati de intarziere (Amenzi, penalitati)',
        '2040' => 'Penalitati judecatoresti (Amenzi, penalitati)',
        '2050' => 'Penalitati zbor (Amenzi, penalitati)',
    ],
    'Asigurari' => [
        '3000' => 'Asigurare Insolventa (Asigurari)',
        '3010' => 'Asigurari Auto (Asigurari)',
        '3020' => 'Asigurari daune materiale (Asigurari)',
        '3030' => 'Asigurari de calatorie (Asigurari)',
        '3040' => 'Asigurari IMM (Asigurari)',
        '3050' => 'Asigurari Incendii (Asigurari)',
        '3060' => 'Asigurari Raspundere Civila (Asigurari)',
    ],
    'Chirie sedii' => [
        '4000' => 'Chirie principala (Chirie sedii)',
        '4010' => 'Marketing (Chirie sedii)',
        '4020' => 'Spatii comune (Chirie sedii)',
    ],
    'Combustibil' => [
        '5000' => 'Alte cheltuieli (Combustibil)',
        '5010' => 'Cheltuieli combustibil (Combustibil)',
    ],
    'Comisioane bancare' => [
        '6000' => 'Cheltuieli bancare (Comisioane bancare)',
        '6010' => 'Comisioane bancare (Comisioane bancare)',
    ],
    'Consumabile' => [
        '7000' => 'Consumabile (Consumabile)',
    ],
    'Deplasare si diurna' => [
        '8000' => 'Alte cheltuieli ( deplasare si diurna )',
        '8010' => 'Diurne si cazari (Deplasare si diurna)',
    ],
    'Deschideri sedii' => [
        '9000' => 'Cheltuieli diverse ( deschidere sedii )',
    ],
    'Dobanzi' => [
        '10000' => 'Dobanzi (Dobanzi)',
    ],
    'Drepturi de autor' => [
        '11000' => 'Cheltuieli drepturi autor (Drepturi de autor)',
    ],
    'Inchirieri' => [
        '12000' => 'Chirii Auto (Inchirieri)',
        '12100' => 'Chirii containere (Inchirieri)',
        '12200' => 'Chirii imprimante (Inchirieri)',
        '12300' => 'Chirii purificator (Inchirieri)',
        '12400' => 'Chirii servere (Inchirieri)',
    ],
    'Infotrip' => [
        '13000' => 'Cheltuieli infotrip (Infotrip)',
    ],
    'Internet' => [
        '14000' => 'Cheltuieli internet (Internet)',
    ],
    'Intretinere si reparatii' => [
        '15000' => 'Cheltuieli intretinere si reparatie (Intretinere si reparatii)',
    ],
    'Marketing si promovare' => [
        '16000' => 'Alte cheltuieli marketing (Marketing si promovare)',
        '16800' => 'Alte cheltuieli productie (Marketing si promovare)',
        '16100' => 'Barter (Marketing si promovare)',
        '16200' => 'Cheltuieli Abonamente (Marketing si promovare)',
        '16300' => 'Cheltuieli Chirie (Marketing si promovare)',
        '16400' => 'Cheltuieli evenimente (Marketing si promovare)',
        '16500' => 'Cheltuieli panotaj (Marketing si promovare)',
        '16600' => 'Cheltuieli printare (Marketing si promovare)',
        '16910' => 'Cheltuieli productie Auto (Marketing si promovare)',
        '16700' => 'Cheltuieli productie cataloage (Marketing si promovare)',
        '16920' => 'Cheltuieli productie video (Marketing si promovare)',
        '16930' => 'Cheltuieli promovare (Marketing si promovare)',
        '16940' => 'Cheltuieli promovare Facebook (Marketing si promovare)',
        '16950' => 'Cheltuieli promovare Google (Marketing si promovare)',
        '16960' => 'Cheltuieli promovare online (Marketing si promovare)',
        '16970' => 'Cheltuieli promovare TV (Marketing si promovare)',
        '16980' => 'Cheltuieli Radio (Marketing si promovare)',
        '16990' => 'Cheltuieli servicii PR (Marketing si promovare)',
        '16991' => 'Cheltuieli transport (marketing) (Marketing si promovare)',
        '16992' => 'Chirii publicitare (Marketing si promovare)',
    ],
    'Obiecte de inventar' => [
        '17000' => 'Alte cheltuieli (obiecte inventar )',
        '17101' => 'Cheltuieli consumabile (Obiecte de inventar)',
        '17100' => 'Cheltuieli mijloace fixe (Obiecte de inventar)',
    ],
    'Prestari servicii' => [
        '18000' => 'Alte cheltuieli ( prestari servicii )',
        '18100' => 'Alte comisioane (prestari servicii)',
        '18200' => 'Alte prestari servicii (Prestari servicii)',
        '18300' => 'Cheltuieli abonamente (prestari servicii)',
        '18400' => 'Cheltuieli arhivare (Prestari servicii)',
        '18500' => 'Cheltuieli Audit (Prestari servicii)',
        '18600' => 'Cheltuieli Call Center (Prestari servicii)',
        '18700' => 'Cheltuieli medicina muncii (Prestari servicii)',
        '18800' => 'Cheltuieli printare ( prestari servicii)',
        '18900' => 'Cheltuieli recrutare personal (Prestari servicii)',
        '18910' => 'Cheltuieli salubrizare (Prestari servicii)',
        '18920' => 'Cheltuieli servicii consultanta (Prestari servicii)',
        '18930' => 'Cheltuieli software (Prestari servicii)',
        '18940' => 'Cheltuieli Training-uri/workshop-uri (Prestari servicii)',
    ],
    'Protocol' => [
        '19000' => 'Alte cheltuieli (protocol)',
        '19100' => 'Cheltuieli campanii (protocol)',
        '19200' => 'Cheltuieli cazare (protocol)',
        '19300' => 'Cheltuieli deplasari (protocol)',
        '19400' => 'Cheltuieli evenimente ( protocol )',
        '19500' => 'Cheltuieli productie ( protocol )',
    ],
    'Salarii si Contributii' => [
        '20000' => 'Alte cheltuieli salariale (salarii+contributii+PFA)',
        '20100' => 'Cheltuieli prime salariale (salarii+contributii+PFA)',
        '20200' => 'Cheltuieli salarii angajati (salarii+contributii+PFA)',
        '20300' => 'Cheltuieli salarii PFA/SRL (salarii+contributii+PFA)',
        '20400' => 'Cheltuieli suport financiar (salarii+contributii+PFA)',
    ],
    'Servicii legale' => [
        '21000' => 'Abonamente (Servicii legale)',
        '21100' => 'Cheltuieli legale (Servicii legale)',
        '21200' => 'Servicii avocat (Servicii legale)',
        '21300' => 'Servicii notar (Servicii legale)',
    ],
    'Sponsorizari' => [
        '22000' => 'Cheltuieli sponsorizare (sponsorizari)',
    ],
    'Taxe si impozite' => [
        '23000' => 'Alte taxe si impozite (taxe si impozite)',
        '23100' => 'Impozit pe profit ( taxe si impozite )',
        '23200' => 'Impozite ( taxe si impozite )',
        '23300' => 'Taxe (taxe si impozite)',
    ],
    'Telefonie, internet si curierat' => [
        '24000' => 'Cheltuieli colocare (telefonie, net si curierat)',
        '24100' => 'Cheltuieli curierat (telefonie, net si curierat)',
        '24200' => 'Cheltuieli telefonie (telefonie, net si curierat)',
    ],
    'Transport' => [
        '25000' => 'Alte cheltuieli de transport (transport)',
        '25100' => 'Cheltuieli deplasari (transport)',
        '25200' => 'Cheltuieli transport (transport)',
    ],
    'Utilitati' => [
        '26000' => 'Cheltuieli utilitati apa (Utilitati)',
        '26100' => 'Cheltuieli utilitati energie (Utilitati)',
        '26200' => 'Cheltuieli utilitati gaz (Utilitati)',
    ],
];
